# Generated by Django 5.2.6 on 2025-09-04 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="task_manager.category",
            ),
            preserve_default=False,
        ),
    ]
