# Generated by Django 5.2.6 on 2025-10-15 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_task_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'Priority', 'verbose_name_plural': 'Priorities'},
        ),
    ]
